### ISSUE TITLE
[메인 - 구민진] 반응형, 모달창 작업

### ISSUE THREAD

**Issue by mingmi9** [Sprint-11-4team/sprint-linkshop#36]
## ✅  저가 이번에 할 작업은 크게 이 두가지 입니다. ( 최대 2일로 잡아주세요)
1. 상점 카드 반응형 작업
2. 상세필터 모달창 작업
3. api 작업
4. 상품순, 최신순, 좋아요순 정렬 

##  🤓  그외에 적고싶은것, 궁금한점
1. 
2.

## 체크리스트 (현재까지 진행된부분 체크로 표시 해주세요)

- [ ] '로고' 버튼을 클릭하면 `/list` 페이지로 이동하세요.(새로고침)
- [ ] 링크 카드는 무한스크롤로 이어지게 하세요.
- [ ] '생성하기' 버튼을 클릭하면 `/linkpost` 페이지로 이동하세요.
- [ ] '상세 필터" 버튼을 클릭하면 상세 필터 모달창이 나타나게 하세요.
- [ ] 상세 필터 모달창에서 등록된 상품순 | 최신순 | 좋아요 순으로 정렬이 가능하게 구현하세요..
- [ ] 검색어에 샵 이름의 일부가 포함되면 검색이 가능하도록 구현하세요..

**Comment by yunrap** [comment]
이때 api 작업도 될수있으면 추가부탁드립니다
모달창이 조금 수정될수있어서 css 부분만 우선 붙여놓는게 좋을거같아요 ㅎㅎ

최신순 좋아요순시 나열될수있게끔 진행 부탁드립니다.🤓
