### ISSUE TITLE
[생성-김성종님] 생성전체 페이지 틀구성

### ISSUE THREAD

**Issue by yunrap** [Sprint-11-4team/sprint-linkshop#8]
노션 글 참고하여 작성하겠습니다.

1. 생성페이지 틀작업 구현 우선 큰틀로잡힌 페이지 부분 하루로 잡아놨습니다..
작업일자를 짧게잡은건 우선 ui적으로 화면이나왔으면해서  2일로잡았습니다. !~ ㅎㅎㅎ

보면 관호님이랑 페이지가 거의 같네요!~ 피그마랑 같게 최대한 구현해주세요!~
관호님이랑 같이 진행하셔서 최대한 같은 css 로 진행하시면될거같아요

**Comment by yunrap** [comment]
테블릿 & 모바일버전도 이때 같이 작업된다면 좋을거같긴합니다.

**Comment by KimLuka** [comment]
어제 시름시름 앓아가지고 태블릿 모바일 버전까지는 어려울 거 같아요 ㅜ

**Comment by yunrap** [comment]
> 어제 시름시름 앓아가지고 태블릿 모바일 버전까지는 어려울 거 같아요 ㅜ

네!~ 아래 커멘트는 추가로 달았습니다!~ ㅎㅎ
요즘 날씨가 추워서 감기 조심하세요 ㅠㅠ 주말에 저도 멍때리다가 지금 정신을 차렸네요!~ ㅎㅎ
내일 재밌게 작업해봐요

저도 모달창을 .... 흐흑!!!난이도가있겠죠??  ㅠㅠ 도전해보겠습니다!
